
name: Bridgecrew

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
   bridgecrew:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Run Bridgecrew
        uses: bridgecrewio/bridgecrew-action@v1.177.2
        with:
          soft_fail: true

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif

      - name: Upload SARIF file as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: bridgecrew-sarif
          path: results.sarif