# This is a basic workflow to help you get started with Actions

name: Checkov

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
   checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Run checkov
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          soft_fail: true

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif

      - name: Upload SARIF file as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: checkov-sarif
          path: results.sarif
